version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
      - MONGODB_URI=mongodb://mongo:27017/habits
      - JWT_SECRET=dev-secret-123
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:3000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
